import type { GameDefinition } from "@withu/shared-types";

export const GAME_CATALOG: GameDefinition[] = [
  {
    key: "tic_tac_toe",
    name: "Tic-Tac-Toe",
    category: "logical",
    description: "The classic 3x3 grid game, made for two.",
    icon: "grid-3x3",
    minPlayers: 2,
    maxPlayers: 2,
    isTurnBased: true,
  },
  {
    key: "connect_four",
    name: "Connect Four",
    category: "logical",
    description: "Drop discs and line up four in a row first.",
    icon: "circle-dot",
    minPlayers: 2,
    maxPlayers: 2,
    isTurnBased: true,
  },
  {
    key: "memory_match",
    name: "Memory Match",
    category: "logical",
    description: "Flip cards together and find every pair.",
    icon: "layout-grid",
    minPlayers: 2,
    maxPlayers: 2,
    isTurnBased: true,
  },
  {
    key: "couple_questions",
    name: "Couple Questions",
    category: "romantic",
    description: "Take turns answering questions about your relationship.",
    icon: "heart-handshake",
    minPlayers: 2,
    maxPlayers: 2,
    isTurnBased: true,
  },
  {
    key: "would_you_rather",
    name: "Would You Rather?",
    category: "romantic",
    description: "Pick a side, then see what your partner chose.",
    icon: "split",
    minPlayers: 2,
    maxPlayers: 2,
    isTurnBased: false,
  },
  {
    key: "this_or_that",
    name: "This or That",
    category: "romantic",
    description: "Quick-fire preferences to see how in sync you are.",
    icon: "shuffle",
    minPlayers: 2,
    maxPlayers: 2,
    isTurnBased: false,
  },
  {
    key: "truth_or_dare",
    name: "Truth or Dare",
    category: "romantic",
    description: "Romantic truths and playful dares for two.",
    icon: "flame",
    minPlayers: 2,
    maxPlayers: 2,
    isTurnBased: true,
  },
  {
    key: "how_well_do_you_know_me",
    name: "How Well Do You Know Me?",
    category: "romantic",
    description: "Test how well you really know each other.",
    icon: "brain",
    minPlayers: 2,
    maxPlayers: 2,
    isTurnBased: true,
  },
];

export const gameByKey = (key: string) => GAME_CATALOG.find((g) => g.key === key);
